project-flotta/flotta-device-worker

- internal/workload/api/api.go
- internal/workload/network/netfilter.go
- internal/workload/workload.go
For workloads that define container host ports, the worker will be
responsible for creating a dedicated netfilter chain and add rules for
incoming IPv4 and IPv6 traffic for the desired ports.
When workload is being removed, the chain will be dropped.
On workload udpdates, the chain of rules will be re-created.
> Support connectivity for workloads

- internal/workload/api/api.go
This PR removes unused interface to simplify the design of the `workload` package and sub-packages.
> Removed unused interface

- internal/workload/api/api.go
- internal/workload/manager.go
- internal/workload/mapping.go
- internal/workload/mapping/mapping.go
- internal/workload/podman/podman.go
- internal/workload/wrapper.go
Fix for ECOPROJECT-234.
This PR introduces file-backed mapping between pod name defined in the pod specification and ID assigned to the Podman pod.
As part of this change set `workloadWrapper` has been moved to a separate file.
> Mapping pod name from spec to Podman pod ID

- README.md
- cmd/device-worker/main.go
- internal/configuration/configuration.go
- internal/volumes/volumes.go
- internal/workload/manager.go
This PR is a first step in implementing data transfer functionality on the device side. 
Code in this PR injects `/export` hostpath mount to each container in each pod specification.  Workloads are expected to put there  files that need to be transferred to the control plane storage.
> Attach export volume

- Makefile
This PR changes the device-worker binary build to allow it to bu run on RHEL (with older GLIBC).
> Added build flags to allow running on RHEL

- cmd/device-worker/main.go
- internal/hardware/hardware.go
- internal/registration/registration.go
This PR introduces registration retry logic in order to address ECOPROJECT-245. The registration requests will be sent to the control plane until device receives its configuration for the first time (as an indication of a successful registration). 
Registration operation is idempotent so it won't affect cluster-side state if request is sent multiple times.
> Retry device registration until configuration is provided by the control plane

- .github/workflows/rpm.yaml
- Makefile
- k4e-agent.spec
RPM was not created correctly, because it ships a binary when this is
not allowed. With this change, the RPM is created from source, and
src.rpm is created.
Also, a new workflow is added, if any new commit on `main` branch, it'll
build the src pacakge, and push the change to Fedora copr[0], where ARM
and x86 builds are triggered.
https://copr.fedorainfracloud.org/coprs/eloyocoto/k4e-test/packages/
@TODO: I need to document how to use this repo, but want to work on r4e image first to get full context. 
> CI: Push rpm to fedora copr

- internal/datatransfer/s3/sync.go
Region store in s3 configuration was not used to configure s3 client.
> Using region from configuration

- cmd/device-worker/main.go
- internal/datatransfer/monitor_test.go
- internal/heartbeat/heartbeat_test.go
- internal/registration/registration_test.go
- internal/workload/manager.go
- internal/workload/manager_test.go
This PR exposes `DEVICE_ID` variable equal to ID under which the device is registered with the control plane to each container in every Pod.
> Passing DEVICE_ID env variable to each container

- cmd/device-worker/main.go
- internal/datatransfer/monitor.go
- internal/datatransfer/monitor_test.go
When device start, the datatransfer/monitor didn't get the update at
all, because Update() was not called.
With this change, on start, we force the start of config load.
Fix ECOPROJECT-376
> Datatransfer: Monitor force config load when device start

- Makefile
- README.md
New makefile with help sections:
```
--> make help
Usage:
make <target>
General
help             Display this help.
Development
test             Run unit test on device worker
test-coverage    Run test and launch coverage tool
generate         Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
clean            Clean project
Build
build            Build device worker
build-arm64      Build device worker for arm64
Deployment
install          Install device-worker
install-arm64    Install device-worker on arm64.
rpm              Create rpm build
rpm-arm64        Create rpm build for arm64
dist             Create distribution packages
-->
```
Related to: https://github.com/jakub-dzon/k4e-operator/pull/37
Related to: ECOPROJECT-285
Signed-off-by: Eloy …
> Makefile: Added help section.

- cmd/device-worker/main.go
With this change, yggradsil logs are a bit easy to understand, due to
the datatime on device worker does not add any information at all, and
add a lot of noise.
```
[yggd] 2021/12/16 13:12:00 [/usr/local/libexec/yggdrasil/device-worker] Data directory: /var/local/yggdrasil/device
[yggd] 2021/12/16 13:12:00 [/usr/local/libexec/yggdrasil/device-worker] Device config file: /var/local/yggdrasil/device/device-config.json
[yggd] 2021/12/16 13:12:00 [/usr/local/libexec/yggdrasil/device-worker] Cannot force-update datatransfer monitor: Cannot retrieve storage info
[yggd] 2021/12/16 13:12:00 [/usr/local/libexec/yggdrasil/device-worker] The heartbeat was started
```
Instead of:
```
[yggd] 2021/12/16 12:57:48 [/usr/local/libexec/yggdrasil/device-worker] 2021/12/16 12:57:48 Data directory: …
```
> Log: disable datatime logging

- internal/workload/manager.go
- internal/workload/manager_test.go
This PR refactors the directory structure that is created on device to store manifests. 
From now on workload manifest and auth configuration file will be stored under workloads/<workload-name> directory.
No backwards compatibility is provided - this is a breaking change.
> Refactor directories

- Makefile
- go.sum
Ginkgo v2 has been released and has been automatically used by `make test`. This PR pins ginkgo version to the latest of 1.x line.
> Pin ginkgo to v1.16.5 due to release of v2

- go.mod
- internal/metrics/scraper.go
- internal/metrics/scraper_test.go
- vendor/modules.txt
This PR introduces `metrics.HTTPScraper` type that is responsible for calling given HTTP endpoint and scraping (retrieving and parsing) metrics in openmetrics format exposed by it.
> Metrics scraper

- internal/configuration/configuration.go
- internal/configuration/configuration_mock.go
- internal/configuration/configuration_test.go
- internal/datatransfer/monitor.go
- internal/datatransfer/monitor_test.go
- internal/heartbeat/heartbeat.go
- internal/metrics/metrics.go
- internal/metrics/system.go
- internal/metrics/workload.go
- internal/workload/manager.go
When yggd restart and any workload is already running, if the config
didn't change, it will not update the config to all registered observers.
With this commit, when an observer is created, has the option to send the
initial config to the Update() method, so the observers can run the initial
config and work against it.
> Config: RegisterObserver init config.

- internal/workload/podman/podman.go
- internal/workload/wrapper.go
- internal/workload/wrapper_test.go
This PR changes the systemd unit names to use pod IDs, because for some
use cases the pod names may not work.
For example when container name and pod name has same for different
podman version the podman generate different pod name.
> Change systemd unit names to pod IDs

- .github/workflows/rpm.yaml
- Makefile
Fixes 2 issues in the Makefile:
* Failure to copy the .tar.gz to the `rpmbuild/SOURCES` directory as the directory does not exist at that point. Using the `install -D` command solves the issue.
* How to reproduce:
* Delete the ~/rpmbuild` directory
* Run `make rpm-build`
* Expected outcome: Successful build
* Actual result: Failed to copy `.tar.gz` to `~/rpmbuild/SOURCES/`
* `make dist` only creates the rpms for a single architecture (when run the second time it will complete the remaining one). I suspect it has to do with the fact that both `rpm` and `rpm-arm64` depend on the same target `rpm-build` and `make` skips calling the `rpm-build` the second time as it has been already completed previously.
*  How To reproduce:
*  Delete the `~/rpmbuild` directory
* Run `make dist`
* Check that …
> Fix make dist

- internal/metrics/allow-list.go
By default, device-worker does not send any information about how many
network bandwidth is using, with this change will report the following
metrics:
```
node_network_receive_bytes_total
node_network_transmit_bytes_total
```
Fix: ECOPROJECT-495
> Metrics: Added more metrics on default allow-list

- internal/metrics/daemon.go
- internal/metrics/daemon_test.go
- internal/metrics/mock_daemon.go
- internal/metrics/system.go
- internal/metrics/system_test.go
- internal/metrics/workload.go
- internal/metrics/workload_test.go
With this commit, users can define what metrics want to to retrieve
on workload level.
Related-to: https://github.com/project-flotta/flotta-operator/commit/5b67dd38215b6a110a6293c9ac35875e9417daa0
Fix: ECOPROJECT-495
> Metrics: Added allowlist filtering

- internal/service/systemd.go
- internal/workload/wrapper.go
Small change on workload wrapper to:
- Send a valid error message to the user, instead cannot parse JSON.
- Unmarshal JSON as struct, due to is not valid parsing JSON to a
interface.
> Workload: Fix error messages

- README.md
Due to some changes in upstream version of yggdrasil, we can't no longer
use the main branch until other PR got merged.
This commit changes how to install yggdrasil and some error messages.
> Doc: fix yggdrasil version

- internal/workload/podman/mock_podman.go
- internal/workload/podman/podman.go
Added a new Log method to Podman interface, so can retrieve log to the
given writer interface with the container ID.
There is new channel per each container, per each pod, and two loops
that read the same Reader, but to have a prefix per each container, we
need to have in this way.
This is needed for the log collection, so pod logs can be send to
another transport in the near future.
> Podman: Added Logs method

- internal/os/os.go
- internal/os/os_test.go
This PR resolves problem described in https://issues.redhat.com/browse/ECOPROJECT-587. And allows for OS configuration to be missing (which is the case before the device is registered).
> Tolerate missing OS configuration

- flotta-agent.spec
- tools/Dockerfile
To be able to test with race conditions enabled and be able to debug
that there is no race-conditions in the integration test at all.
Related-to: https://issues.redhat.com/browse/ECOPROJECT-473
> RPM: Build flotta-agent-race package

- cmd/device-worker/main.go
- internal/logs/log_container.go
- internal/logs/log_container_test.go
- internal/logs/logs_suite_test.go
- internal/logs/syslog_transport.go
- internal/logs/transport.go
- internal/logs/workload.go
- internal/logs/workload_test.go
- internal/logs/workload_writer.go
- internal/logs/workload_writer_test.go
- internal/workload/manager.go
- internal/workload/mock_wrapper.go
- internal/workload/wrapper.go
This PR adds a way to send logs to a Syslog server, or any other platform that implements the interface in the future.
The main goal is to read Pod logs and store them on an intermediate struct (Fifolog) that buffers (With limits defined by a user) and sends it to the given server with retries, etc.. 
Users can define multiple Syslog servers at the device level, like: 
```
apiVersion: management.project-flotta.io/v1alpha1
kind: EdgeDevice
metadata:
name: XXXX
namespace: default
spec:
log_collection:
syslog:
BufferSize: 10
kind: syslog
syslogConfig:
address: dc1-log.acme.org:601
proto: tcp
importantLogs:
BufferSize: 1000
kind: syslog
syslogConfig:
address: custom-syslog.acme.org:601
proto: tcp
``` 
And assign log transport on the deploy side using this format: 
```
---
apiVersion: …
```
> Collect Workload logs

- Makefile
- README.md
Removed the requirement for root permissions in `make install`.
Added `make uninstall`.
Replaced the path of `LIBEXECDIR` and `SYSCONFDIR` to be under `/var` instead of `/usr`.
Added documentation regarding all the above to the `README`.
Signed-off-by: arielireni <aireni@redhat.com>
> Update `make install`

- internal/server/deviceserver.go
This PR adds locking on handling of configuration messages to avoid unnecessary duplicate configuration updates.
Issue has been described in https://issues.redhat.com/browse/ECOPROJECT-284
> Avoid duplicate configuration updates at the cost of increased contention

- Makefile
Just add a way to bump operator version easily to the latest commit
without to much pain.
> feat: makefile add bump_operator target

- tools/Dockerfile
Using the right target url for testing, in this case project-flotta.io,
to mach the domain.A followup PR on operator to add the hostname on
container run.
Fix: https://issues.redhat.com/browse/ECOPROJECT-399
> Test: Fix target url for yggdrasil

- internal/configuration/configuration_test.go
AfterEach function doesn't check the os.Remove error.
In addition the os.Remove fails always because the directory is never
empty.
Replace os.Remove with os.RemoveAll fixes the problem.
To be sure to have the permission to delete the folder, this PR also
invokes os.Chmod function.
Signed-off-by: Gloria Ciavarrini <gciavarrini@redhat.com>
> Fix: AfterEach in configuration_test doesn't delete datadir

- tools/Dockerfile
When testing integration, if quay is down or slow can affect our e2e
test, so in this case, I added the image in there, so no download issue
can affect the CI.
> Dockerfile: pull nginx image for speed the testing

- go.mod
- go.sum
- vendor/github.com/project-flotta/flotta-operator/models/workload.go
- vendor/github.com/project-flotta/flotta-operator/pkg/mtls/ca.go
- vendor/github.com/project-flotta/flotta-operator/pkg/mtls/caprovider_secret.go
- vendor/modules.txt
Set operator version to commit 43205a5e4cbf5c90fcd3241e23d4c0a943f509a2
Flotta agent requires at least changes introduced with [#project-flotta/flotta-operator/#115](https://github.com/project-flotta/flotta-operator/pull/115)
Signed-off-by: Gloria Ciavarrini <gciavarrini@redhat.com>
> Fix: Bump operator version to the latest commit

- go.mod
- go.sum
- internal/metrics/remote_write.go
- internal/metrics/remote_write_test.go
- vendor/github.com/project-flotta/flotta-operator/models/metrics_receiver_configuration.go
- vendor/modules.txt
Pass an optional CA to the device
This is the CA that signs the metrics receiver's certificate
https://issues.redhat.com/browse/ECOPROJECT-579
enable TLS in device remote write
> enable TLS for metrics remote writer

- internal/registration/registration.go
When re-register there is no need to call the config instance, due there
is async process by the yggdrasil heartbeat, and it has a race condition
on the approval process.
> Registration: no need to call config

- internal/workload/podman/mock_podman.go
- internal/workload/podman/podman.go
- internal/workload/wrapper.go
- internal/workload/wrapper_test.go
This commit add special systemd service configuration for the pods which
are configured to use autoupdate podman feature. The reason for this is
that podman `generate systemd` command doesnt' support generation of the
services for pod, which were created via API, or via podman play kube.
Default service generation only restarts the pod, while this custom
configuration re-create the container so the newer image could be used.
> Use custom systemd service configuration for autoupdate

- .gitignore
- Makefile
- cmd/device-worker/main.go
- config/device-worker.toml
- flotta-agent.spec
- go.mod
- internal/service/systemd.go
- internal/workload/podman/podman.go
- internal/workload/wrapper.go
- internal/workload/wrapper_test.go
- tools/Dockerfile
- tools/testing/Dockerfile
- vendor/modules.txt
This commit add support for rootless podman.
There are multiple things needed to support rootless podman:
0) Create a user running the podman, flotta in our case.
1) Enable linger for the user, so systemd can run even without session.
2) Have set the /etc/subuid /etc/subgid for the user.
3) Create home directory for the user, to store the data and systemd
services.
4) Enable podman.socket for the user.
5) Volumes directory must be owned by the user, as podman use it, not
root.
Those prerequsites are done in spec file. For RPM based installation by
default the device-worker will execute podman as rootless. For dev-env
user will still use the rootfull pods. This could be changed the env
variables in the 'config/device-worker.toml'. We introduced two new env
variables:
- HOME - store the …
> Rootless podman

- tools/Dockerfile
This patch remove the pulling of the nginx image.
It doesn't work in the CI for flotta user:
`time="2022-04-27T06:31:32Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
Error: cannot setup namespace using newuidmap: exit status 1
`
> Remove pulling of podman nginx image

- Makefile
- cmd/device-worker/main.go
- config/device-worker.toml
- flotta-agent.spec
- internal/service/systemd.go
- internal/workload/podman/podman.go
This patch add custom XDG_RUNTIME_DIR so user can customize it as
needed. For RPM installation we use flotta user XDG_RUNTIME_DIR env var
unless user overwrite it.
> Use custom XDG_RUNTIME_DIR

- go.mod
- internal/workload/podman/podman.go
- vendor/modules.txt
Add _pod suffix for pods only in case podman version is less then 4.0
and only in case the pod and container names are the same.
> Don't generate _pod suffix for all pods

- flotta-agent.spec
Since we do support metrics and ansible, we should require dependencies so the features work. We print warnings when those features don't work if those packages are not installed, but we don't provide any documentation to add it add hoc. So would be better to require it during installation.
> Add RPM req for ansible and node_exporter

- internal/registration/certs.go
- internal/registration/registration.go
- internal/registration/registration_test.go
This PR fixes the datarace when deregistering device detected byu  @jakub-dzon 
Basic refactoring was also performed:
- split methods into smaller methods
- reorganized/realigned structs fields of the registration package
- fix warnings
Signed-off-by: Gabriel Farache [gfarache@redhat.com](mailto:gfarache@redhat.com)
> Fix datarace when deregister and refactor

- internal/heartbeat/heartbeat.go
- internal/heartbeat/heartbeat_test.go
This PR fixes the data races detected by @jakub-dzon and it implements a change in the Update behaviour: the ticker will only be reseted if the configuration (more precisely, the PeriodSeconds field) changed.
Signed-off-by: Gabriel Farache [gfarache@redhat.com](mailto:gfarache@redhat.com)
> Fix heartbeat races and reset ticker only if configuration changed

- internal/metrics/workload.go
the fiels latestConfig is not used
the log line prints the pointer addresses upon every call to Update
https://issues.redhat.com/browse/ECOPROJECT-829
> removing log and struct field

- internal/workload/podman/podman.go
it is better to avoid closing channels
https://issues.redhat.com/browse/ECOPROJECT-837
> do not close channels in function conatinerLog

- cmd/device-worker/main.go
- flotta-agent.spec
The PR fixes several issues with device-worker:
* It adds executable permissions to .config folder:
Without +x, no access can be made to the folder and files cannot be
created in.
* Uses `id -u flotta` to obtain flotta user ID.
* Disables selinux as a workaround to failure to start podman.socket as
flotta user. This issue is reported in
bug https://bugzilla.redhat.com/show_bug.cgi?id=2060702
* Remove `systemctl user@...` since user systemd is controller by
loginctl.
> Fix issues with running device-worker

- internal/metrics/system.go
- internal/service/systemd.go
- internal/workload/podman/podman.go
- internal/workload/wrapper.go
systemd struct has a field of type pointer to dbus conneciton
it is only assigned when creating a workload
however, it is used when deleting/updating a workload and upon startup
If you create a workload, restart the device-worker, update/delete a workload
then the device-worker will crash.
https://issues.redhat.com/browse/ECOPROJECT-859
> fix panic/crash when deleting workload

- packaging/systemd/flotta.conf
This change adds the home user that it's own by the flotta user.
> RPM: Add flotta home folder on tmpfiles

- .github/workflows/rpm.yaml
- Makefile
- flotta-agent.spec
Added `-race` to the `go build` command to build the race rpm with the race flag enabled.
> Add missing '-race' flag to go build for race rpm

- .github/workflows/artifacts.yaml
There is two actions called RPM Build and it's always hard to know what
is doing each one when you review the jobs.
> Actions: change name

- flotta-agent.spec
- packaging/systemd/flotta-agent.service
- packaging/systemd/flotta-agent.sysusers
When enabling sysusers.d on commit
5b66ac05fc27f4a08be7ae4a28a629fde6d60ea3  flotta user was created, but
the user was system and the entries on /etc/subgid was not created at
all.
With this change, a new system unit file will be created just before
systemd logind service, so user is created and lingered on the first
boot.
> RPM: systemd service for creating users

- .github/workflows/artifacts.yaml
- packaging/systemd/flotta-agent.service
Because now the tmpfiles are trying to use flotta user, but we cannot
use sysusers anymore it's failing on the first boot and the flotta user
cannot run podman socket. This PR fix the flotta unit to create folders.
> Fix: Run tmpfiles on flotta-agent service

- internal/workload/manager.go
When rootless mode is enabled, the agent can write with user flotta, and
cannot deploy users at all.
Error discovered in the following build:
https://github.com/project-flotta/flotta-operator/runs/7169176474?check_suite_focus=true
With error:
```
2022-07-02T19:42:43.4576409Z     Jul 02 19:39:40 304de5a240b8 podman[192]: time="2022-07-02T19:39:40Z" level=info msg="Request Failed(Internal Server Error): error playing YAML file: failed to create volume \"export-nginx\": mkdir /etc/yggdrasil/device/volumes/nginx: permission denied"
```
> Folders: Enable full write permissions

- .github/workflows/go.yml
- Makefile
- internal/common/test_utils.go
- internal/configuration/configuration_test.go
- internal/workload/manager_test.go
- tools/Dockerfile_test
This PR adds a new target `test-docker` which executes all the test in a rootfull contiainer.
> Add target to run rootfull test container

- go.mod
- go.sum
- internal/workload/manager.go
- vendor/github.com/project-flotta/flotta-operator/models/workload.go
- vendor/github.com/project-flotta/flotta-operator/pkg/mtls/ca.go
- vendor/modules.txt
* Bumped flotta-operator to [b925a42628d2](https://github.com/project-flotta/flotta-device-worker/commit/473da65728bca77cb391931070a5b48a358ee233)
* Added code to propagate the annotations defined in the workload to the pod manifest.
> Propagate annotations to the pod manifest

- internal/registration/registration_test.go
The registration test assumes path /etc/yggdrasil is reachable and
can be written to.
For that purpose, the test should be marked with root label to be
executed with the required permissions.
> Add root label to registration test

- internal/configuration/configuration.go
- internal/mount/info.go
- packaging/systemd/flotta-agent.service
- packaging/systemd/flotta.conf
The PR fixes errors of flotta-agent installation.
As part of the installation, flotta-agent service started and failed.
When selinux is enabled, post-script fails to create flotta user with error:
```
Jul 11 13:16:05 fedora useradd[3106]: new user: name=flotta, UID=1001, GID=1001, home=/var/home/flotta, shell=/sbin/nologin, from=none
Jul 11 13:16:05 fedora useradd[3106]: failed adding user 'flotta', exit code: 12
Jul 11 13:16:05 fedora bash[3106]: useradd: cannot create directory /var/home
```
The folder _/var/home/flotta_ requires updates to its selinux labels. To fix, we add
the label _user_home_dir_t_ to the folder  in order to serve as flotta's home directory.
In addition, certain flags changed for _useradd_ command to specify the base 
directory and also flag to instruct the creation …
> Fix agent installation

- internal/os/greenboot_scripts.go
When doing an upgrade using Ostree the greenboot file is added
correctly, but with the rootless podman things started to fail because
it's not correctly defined by podman.
It's using sudo instead of machinectl because it's not part of RHEL 9
default.
> Fix: greenboot command with rootless podman

- packaging/systemd/flotta-agent.service
Adds the exclusion of `/var/lib/dnf` from the temp file cleanup processed by `systemd-tmpfiles`. This directory contains the `rpmdb_lock.pid` file that is created during the transation in which dnf installs flotta-agent.
> Fix [Errno 2] No such file or directory: '/var/lib/dnf/rpmdb_lock.pid'

- packaging/systemd/flotta-agent.service
Systemd-tmpfiles set /run/nologin on
/usr/lib/tmpfiles.d/systemd-nologin.conf to booting up, with this change
/run/nologin will not be executed at all.
> Systemd: Fix nologin

- go.mod
- internal/workload/podman/podman.go
- tools/Dockerfile
- vendor/modules.txt
Now device needs podman 4.2, so make explicit on the code.
At the moment there is no 4.2 container, so we need to use testing one.
> Fix: Require podman 4.2

- tools/Dockerfile
The images on quay.io/podman/testing:ae7690c42379 are deleted after a
while, so I get the image and put it on project-flotta quay account
Failed CI entry:
https://github.com/project-flotta/flotta-device-worker/runs/7436420630?check_suite_focus=true
> Dockerfile: using flotta image

- internal/workload/wrapper.go
When running on systemd some leftovers are on
`/var/home/flotta/.config/systemd/user/default.target.wants/` mainly
because service is deleted, but the symlink is not deleted at all.
> Fix: systemd workload disable

- flotta-agent.spec
The version is in a different format, example of build:
```
%define _build_id_links none
%global flotta_systemd packaging/systemd
%global flotta_user flotta
Name:       eloy
Version:    0.2.0
Release:    3%{?dist}
Summary:    Agent application for the Flotta Edge Management solution
ExclusiveArch: %{go_arches}
Group:      Flotta
License:    ASL 2.0
Requires:       podman >= 4:4.2.0
Provides:       %{name} = %{version}-%{release}
Provides:       golang(%{go_import_path}) = %{version}-%{release}
%description
eloy
%prep
ls
%build
touch test.txt
%install
mkdir -p %{buildroot}/var/log/
cp test.txt  %{buildroot}/var/log/
%files
/var/log/test.txt
%changelog
* Tue Jul 26 2022 Eloy Coto <eloycoto@acalustra.com> 0.2.0-3
- Fix containers startup on systemd
* Tue Jul 26 2022 Moti Asayag …
```
> RPM: fix podman version dependency

- tools/Dockerfile
Updated edgedevice image to use podman v4.2.0-rc3.
Build of base image done by using the following Dockerfile:
```
FROM quay.io/podman/upstream:latest
RUN dnf -y remove podman
RUN dnf -y install --best podman --enablerepo=updates-testing --disablerepo=copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next
```
Image pushed to quay.io/project-flotta/podman:v4.2.0-rc3-dev
Changes were made to edgedevice Dockerfile since the configuration file located in a different location and few tweaks were needed.
> Upgrade podman image version to v4.2.0-rc3

- tools/Dockerfile
The base image was updated in quay.io/project-flotta
which has the containers.conf under /etc/containers/container.conf
Also adding less utility to ease the debug.
> Use podman latest as base image for edgedevice

- Makefile
On commit 0b745d15a3718a458e508712cc7f5b3ce8b0bf14 I didn't push all the
changes in the Makefile :facepalm:
> Fix: typo in Makefile
