- internal/workload/manager.go
This PR introduces code that makes sure that workloads that are removed from configuration are removed from the device.
> ECOPROJECT-237 Removing undeployed workloads

- internal/workload/manager.go
Resolves race condition between `WorkloadManagerUpdate` and `WorkloadManager.ensureWorkloadsFromManifestsAreRunning`.
> [ECOPROJECT-235] Resolve race condition 

- Makefile
- go.mod
- go.sum
- internal/volumes/volumes_suite_test.go
- internal/volumes/volumes_test.go
- internal/workload/mapping/mapping.go
- internal/workload/mapping/mapping_suite_test.go
- internal/workload/mapping/mapping_test.go
This PR introduces usage of Ginkgo as a testing framework and provides first two test suites.
Use `make test` to execute all tests.
> [ECOPROJECT-266] Configure testing framework

- internal/workload/wrapper.go
> Log error when failed to delete a chain

- internal/workload/network/netfilter.go
> Delete chain only if exists

- internal/workload/manager.go
> Report workload removal completed

- cmd/device-worker/main.go
> Remove redundant error from message

- cmd/device-worker/main.go
> Use log message without formatting

- internal/server/deviceserver.go
> Rephrase error message

- Makefile
- cmd/device-worker/main.go
Two commits in this PR, not sure if it's the way that you used to work, but detailed information on each commit message:
1) Small change on Makefile to make it easier to run on fedora.
2) Small logging changes to add context to error messages.
Thanks!
> Tiny improvements

- Makefile
> Added verbs for building and installing arm64 version

- Makefile
> Added aarch64 rpm building verb

- internal/heartbeat/heartbeat_test.go
Add missing tests where the list of workloads is correctly retrieved and
reported as expected, or cannot retrieve the list at all....
Fix ECOPROJECT-279
> Heartbeat: Add missing tests

- go.mod
- go.sum
- internal/datatransfer/s3/sync.go
- vendor/github.com/jakub-dzon/k4e-operator/models/s3_storage_configuration.go
- vendor/modules.txt
https://issues.redhat.com/browse/ECOPROJECT-272
> read s3 bucket region sent by server

- README.md
Signed-off-by: Gloria Ciavarrini <gciavarrini@redhat.com>
> README: add missing option in starting yggdrasil command

- Makefile
> Add missing call to rpm-tarball from rpm-src

- .github/workflows/go.yml
> Fix: add a check on generated files

- cmd/device-worker/main.go
- internal/configuration/configuration.go
- internal/configuration/configuration_test.go
- internal/datatransfer/monitor.go
- internal/datatransfer/monitor_test.go
- internal/datatransfer/s3/sync.go
- internal/heartbeat/heartbeat.go
- internal/heartbeat/heartbeat_test.go
- internal/registration/registration.go
- internal/registration/registration_test.go
- internal/server/deviceserver.go
- internal/volumes/volumes_test.go
- internal/workload/manager.go
- internal/workload/manager_test.go
- internal/workload/mapping/mapping.go
- internal/workload/mapping/mapping_test.go
- internal/workload/wrapper.go
Signed-off-by: Gloria Ciavarrini gciavarrini@redhat.com
> Add context to each log message

- Makefile
- internal/registration/registration.go
When running --race options some race-conditions can be found in the
system. This commits adds two things:
1) Tests with --race conditions and their fixes.
2) make build-debug and make install-debug to run device-worker with
race conditions to be able to detect this cases.
> Tooling: Running --race options.

- internal/workload/mapping/mapping.go
- internal/workload/mapping/mapping_test.go
- internal/workload/wrapper.go
This PR add mappingrepository interface, so we can mock it to properly test: #54
> Create a mappingrepository interface so we can mock it

- Makefile
> Vendor: Fix makefile target

- Makefile
> PHONY: Fix issues with make rpm

- internal/hardware/hardware.go
Do not send unnecessary hadware information
Keep the API as is for now
https://issues.redhat.com/browse/ECOPROJECT-327
> Evaluate collected hardware info

- cmd/device-worker/main.go
- internal/metrics/system.go
- internal/metrics/system_test.go
- internal/registration/registration.go
- internal/registration/registration_test.go
Triggers system metrics watcher de-registration.
> System metrics deregistration

- internal/datatransfer/monitor.go
- internal/datatransfer/monitor_test.go
- internal/workload/mapping/mapping.go
- internal/workload/wrapper.go
This PR removes reporting unnecessary and/oror misleading errors.
> Removing unnecessary errors

- .github/workflows/go.yml
- Makefile
- cmd/device-worker/main.go
- internal/configuration/configuration.go
- internal/datatransfer/monitor.go
- internal/datatransfer/monitor_test.go
- internal/datatransfer/s3/sync.go
- internal/metrics/daemon.go
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
- internal/metrics/scraper.go
- internal/metrics/system.go
- internal/metrics/workload.go
- internal/metrics/workload_test.go
- internal/os/os.go
- internal/service/systemd.go
- internal/workload/manager.go
- internal/workload/manager_test.go
- internal/workload/mapping/mapping.go
- internal/workload/podman/podman.go
- internal/workload/wrapper.go
> CI: added gosec and golangci

- go.sum
- internal/registration/registration_test.go
- internal/service/mock_systemd_manager.go
- internal/service/systemd.go
- internal/workload/manager.go
- internal/workload/mock_wrapper.go
- internal/workload/wrapper.go
> Remove services file on unregister

- Makefile
Action failed due to invalid project: 
https://github.com/project-flotta/flotta-device-worker/actions/runs/1826040760
> Makefile: fix copr typo

- .github/workflows/container.yaml
- Makefile
- tools/Dockerfile
This commit add a new workflow job to build the container image for the
e2e tests.
> Add test image build after PR merge

- flotta-agent.spec
> Update rpm source

- internal/service/systemd.go
This PR fixes problem described in [ECOPROJECT-586](https://issues.redhat.com/browse/ECOPROJECT-586)
> Fix systemd config file removal

- tools/Dockerfile
> Don't start yggdrasil in test docker image

- internal/configuration/configuration.go
- internal/service/systemd.go
- internal/workload/wrapper.go
Hi, 
Two commits about race-conditions
Two commits with error messages, that I found. 
Regards
> Race conditions fixes

- internal/datatransfer/monitor.go
> Don't flood logs with Cannot sync paths: nil

- internal/registration/registration.go
Fix a few logs messages that are not helpful to debug.
> Registration: better logs messages

- README.md
> Doc: Fix yggdrasil version

- tools/Dockerfile
> Dockerfile: pull nginx docker image from flotta org

- tools/Dockerfile
> Use ipcns=private for rootless containers

- internal/workload/podman/podman.go
> Generate systemd service suffix same as pod

- .github/workflows/artifacts.yaml
- Makefile
- tools/Dockerfile
> Use copr flotta-testing repo for main branch

- Makefile
When installing device-worker we should follow the same way as
YGGDrasild, and using /var/ is not a option at all because YGGdrasild is
not using like that:
https://github.com/RedHatInsights/yggdrasil/blob/cdde836c519ac72302714b5f7ae90e45de7c79a7/Makefile#L29-L39
On RPM, because prefix is set, there is no problem.
> Makefile: Fix issues with paths

- .gitignore
> Add tar.gz to .gitignore

- flotta-agent.spec
To match the license on github repo.
> Add Apache license to RPM spec

- Makefile
- flotta-agent.spec
> Release 0.1.0

- README.md
This Readme is not longer up to date, move to the web.
> Doc: Remove docs and point to the web

- .github/workflows/rpm.yaml
This commit add github workflow to build RPM per each PR for testing
purposes of the manual flotta-operator job.
> Build RPM per each PR for testing

- internal/logs/log_container.go
- internal/logs/workload.go
This PR fixes the datarace on device startup detected byu @jakub-dzon
Signed-off-by: Gabriel Farache [gfarache@redhat.com](mailto:gfarache@redhat.com)
> Fix data race on startup

- internal/workload/podman/podman.go
transportLog in logs/workload.go sleeps for 100 milli when there's no more data
we need to do the same here
see test results here https://docs.google.com/spreadsheets/d/19AK-GxVl_egGC3bN1DekSf76p1CPMJoC05lmCRUJSAM/edit?usp=sharing
https://issues.redhat.com/browse/ECOPROJECT-821
> Logs function consumes 100% CPU

- internal/workload/podman/podman.go
https://issues.redhat.com/browse/ECOPROJECT-828
log collection merges/concatenates multiple lines
> fix: log collection merges multiple lines

- .github/workflows/rhel-rpm.yaml
- flotta-agent.spec
- tools/ubi-Dockerfile
To avoid last seen issues with different packages, etc.. missing
packages and a bunch of different issues that we faced over last weeks.
Fix: 0c2e1a963f67ebbc072e00d16f2c0fceb62d0025
https://copr.fedorainfracloud.org/coprs/project-flotta/flotta-testing/build/4571305/
> CI: Add RHEL build on device

- .github/workflows/artifacts.yaml
> CI: delete old copr builds

- internal/configuration/configuration.go
whenever configuration changes log old and new configuration
https://issues.redhat.com/browse/ECOPROJECT-825
> log configuration changes

- .github/workflows/artifacts.yaml
- packaging/systemd/flotta-agent.service
This is the same as #191 but I set the wrong target branch :facepalm:
> Fix: Run tmpfiles on flotta-agent files 

- packaging/systemd/flotta-agent.service
A small hotfix to try to achieve the installation without issues, proper
fix to be added on the #200
> Systemd: Fix issues with selinux

- internal/mount/info.go
- internal/mount/mount.go
> Use error interface instead of pointer

- Makefile
- flotta-agent.spec
The release includes the following features:
- Added support for rootless podman
- Added support for host devices
> Release v0.2.0

- internal/service/systemd.go
- internal/workload/wrapper.go
- internal/workload/wrapper_test.go
For betting logging on the device level.
> Fix: Systemd add better logging

- flotta-agent.spec
> RPM: require podman 4.2 version

- .github/workflows/rhel-rpm.yaml
- tools/f36-Dockerfile
> Deprecate support of fc35

- Makefile
- flotta-agent.spec
> Bump version to 0.2.0-2

- Makefile
- flotta-agent.spec
- internal/workload/podman/mock_podman.go
- internal/workload/podman/podman.go
- internal/workload/wrapper.go
- internal/workload/wrapper_test.go
Report events on the channel and avoid to run Run on podman to avoid
conflicts with Systemd.
> Fix: Podman event when start

- .github/workflows/rpm.yaml
- tools/ubi-Dockerfile
Remove redundant steps and packages from rpm build and from ubi8 based images.
> Update github actions

- internal/workload/network/netfilter.go
> Fixes nft keyword collision

- README.md
> Add badges to project to reflect its status

- internal/workload/network/netfilter.go
Fixes https://github.com/project-flotta/flotta-device-worker/issues/232
> Add rule fails due to incorrect chain name

- internal/workload/wrapper.go
> Fix: added more logging on systemd start

- Makefile
Small fix to install gojsonschema in bin/gojsonschema and do not add it
to the vendor at all
> fix: makefile fixes
